# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeMovies' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeMovies
  pod 'XCDYouTubeKit', '~> 2.5'

  target 'NativeMovies-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end